### ISSUE TITLE
Wikidata Plugin Error

### ISSUE THREAD

**Issue by dmromanov** [musicbrainz/picard-plugins#141]
For some tracks wikidata plugin freezes Picard. Here's the debug log entry.

```
I: 15:28:35 WIKIDATA: fetching the folowing url wikidata.org/wiki/Special:EntityData/Q640529.rdf
Traceback (most recent call last):
  File "/usr/lib/picard/picard/webservice.py", line 315, in _process_reply
    self._handle_reply(reply, request, handler, xml, refresh)
  File "/usr/lib/picard/picard/webservice.py", line 304, in _handle_reply
    handler(document, reply, error)
  File "/home/dimon3000/.config/MusicBrainz/Picard/plugins/wikidata.zip/wikidata.py", line 196, in parse_wikidata_response
KeyError: u'fc2755ef-937d-3b95-8977-a4f64bd80243'
```

**Comment by mineo** [comment]
I'm not sure what the official issue tracker for plugins is, but https://tickets.metabrainz.org/browse/PICARD-1166 looks similar to this.

**Comment by dmromanov** [comment]
According to a comment in that task the issue belongs here.

**Comment by mineo** [comment]
This caused by https://github.com/metabrainz/picard-plugins/blob/2.0/plugins/wikidata/wikidata.py#L98-L105. Those lines call `process_wikidata`, which calls `ws.get` with `parse_wikidata_response` as the callback. The problem is that `parse_wikidata_response` assumes that for each request there's some data in `self.taggers`, which is not true in this case, since all requests started by `musicbrainz_release_lookup` do not put any data in there by themselves. I've yet to find out why it should be allowed to start requests at that point without touching `self.taggers`.

**Comment by zas** [comment]
Is it related to https://tickets.metabrainz.org/browse/PICARD-1180 too ?

**Comment by zas** [comment]
> I'm not sure what the official issue tracker for plugins is

Picard plugins are considered as third-party stuff, and therefore it is up to plugin maintainers to manage their own bug tracking. That said, the current situation is hardly satisfying, we have bug reports on Picard JIRA for plugin misbehavior because users aren't always able to differentiate if the issue come from Picard or a plugin... we can't blame them for that. Plus many plugins are actually maintained by Picard Team.

So for now, it is here.

**Comment by dns53** [comment]
This is a bug where the item in musicbrainz has multiple wikidata items linked so multiple requests are made to wikidata.

I have a few things wrong with the current code:
- The number of outstanding requests is not properly counted so when the second request is made the count is out of sync.
- i am keeping track of outstanding requests in a variable in a map, this should probably be a map with a list. when I remove the reference in one thread it is gone in the second thread is still running we get this error.

**Comment by faminebadger** [comment]
Er, that commit is badly broken.

e.g. It adds a loop through self.taggers (line 125), but there is no longer any such variable - it's self.albums now.

Also the log.debug below the same loop clearly belongs inside it, but is currently not, so there is also no such variable "tagger".

Clearly this hasn't been tested in any way.

**Comment by dns53** [comment]
This is fixed by mineo the picard 2 branch, I have not bothered to back port the changes to the 1 branch.

**Comment by akovia** [comment]
Just a heads up this is still happening, or something similar at least.

```
$ picard --version
MusicBrainz Picard 2.0.4
```

```
I: 14:32:38,948 /home/akovia/.config/MusicBrainz/Picard/plugins/wikidata.zip/wikidata.parse_wikidata_response:171: WIKIDATA: final list of genre: ['Post-Disco']
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/picard/webservice/__init__.py", line 426, in _process_reply
    self._handle_reply(reply, request)
  File "/usr/lib/python3.7/site-packages/picard/webservice/__init__.py", line 413, in _handle_reply
    handler(document, reply, error)
  File "/home/akovia/.config/MusicBrainz/Picard/plugins/wikidata.zip/wikidata.py", line 174, in parse_wikidata_response
KeyError: '295553ab-7acb-4376-b952-39af863fabc3'
Aborted (core dumped)
```

**Comment by phw** [comment]
Fixed by #169 (not yet published on the website)
